# Tensor

In [63]:
import torch

## Generating Tensor

In [64]:
a = torch.empty(2, 3)

In [65]:
type(a)

torch.Tensor

In [66]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [67]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [68]:
torch.rand(2,3)

tensor([[0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [69]:
print('Single randn ', torch.randn(2))
print('Double randn ', torch.randn(2,3))
print('Triple randn ', torch.randn(2,3,1))


Single randn  tensor([1.5231, 0.6647])
Double randn  tensor([[-1.0324, -0.2770, -0.1671],
        [-0.1079, -1.4285, -0.2810]])
Triple randn  tensor([[[ 0.7489],
         [ 1.1164],
         [ 1.2931]],

        [[ 0.4137],
         [-0.5710],
         [-0.9749]]])


In [70]:
torch.manual_seed(42)
torch.rand(3)

tensor([0.8823, 0.9150, 0.3829])

In [71]:
torch.manual_seed(42)
torch.rand(3)

tensor([0.8823, 0.9150, 0.3829])

In [72]:
torch.Tensor([1,2,3,4])
torch.Tensor([
    [2,3,4,10],
    [4,3,2,1],
])

tensor([[ 2.,  3.,  4., 10.],
        [ 4.,  3.,  2.,  1.]])

In [73]:
torch.arange(1, 21)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [74]:
torch.linspace(0, 10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [75]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [76]:
torch.full((5,5), 10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

## Tensor Shapes

In [77]:
x = torch.Tensor([[2,6,8], [4,1,5]])
x

tensor([[2., 6., 8.],
        [4., 1., 5.]])

In [79]:
x.shape

torch.Size([2, 3])

In [78]:
torch.empty_like(x)

tensor([[ 0.7489,  1.1164,  1.2931],
        [ 0.4137, -0.5710, -0.9749]])

In [80]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [81]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [83]:
torch.full_like(x, 10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [95]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

# Tensor Data types

In [85]:
x.dtype

torch.float32

In [91]:
y = torch.tensor([1.,2.,3.], dtype=torch.float32)
y.dtype

torch.float32

In [92]:
y.to(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

# Mathematical Operation

In [97]:
x+1

tensor([[3., 7., 9.],
        [5., 2., 6.]])

In [98]:
x-1

tensor([[1., 5., 7.],
        [3., 0., 4.]])

In [100]:
x*100

tensor([[200., 600., 800.],
        [400., 100., 500.]])

In [101]:
x/3

tensor([[0.6667, 2.0000, 2.6667],
        [1.3333, 0.3333, 1.6667]])

In [102]:
x//3

tensor([[0., 2., 2.],
        [1., 0., 1.]])

In [103]:
x**3

tensor([[  8., 216., 512.],
        [ 64.,   1., 125.]])

In [106]:
a = torch.tensor([
    [1,3],
    [5,7]
])
b = torch.tensor([
    [2,4],
    [6,8]
])

Element wise

In [111]:
a + b
a - b
a * b
a / b

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])

In [113]:
torch.neg(a)

tensor([[-1, -3],
        [-5, -7]])

In [114]:
torch.abs(a)

tensor([[1, 3],
        [5, 7]])

In [117]:
c = torch.randn(2,2)
c

tensor([[-0.1671, -0.1079],
        [-1.4285, -0.2810]])

In [118]:
torch.abs(c)

tensor([[0.1671, 0.1079],
        [1.4285, 0.2810]])

In [119]:
torch.round(c)

tensor([[-0., -0.],
        [-1., -0.]])

In [120]:
torch.ceil(c)

tensor([[-0., -0.],
        [-1., -0.]])

In [121]:
torch.floor(c)

tensor([[-1., -1.],
        [-2., -1.]])

In [125]:
torch.clamp(c, min=-1, max=1)

tensor([[-0.1671, -0.1079],
        [-1.0000, -0.2810]])

Reduction Operations

In [135]:
a=a.to(dtype=torch.float32)

In [ ]:
torch.sum(a)

# colums sum
torch.sum(a, dim=0)

# row sum
torch.sum(a, dim=1)

# mean
torch.mean(a)
torch.mean(a, dim=1)
torch.mean(a, dim=0)

# standard deviation
torch.std(a)
torch.std(a, dim=1)
torch.std(a, dim=0)

# product
torch.prod(a)


# argmax
torch.argmax(a)

# argmin
torch.argmin(a)

tensor(0)

In [148]:
a = a.to(dtype=torch.float32)
b = b.to(dtype=torch.float32)

In [149]:
# martix multiplication
torch.matmul(a,b)

tensor([[20., 28.],
        [52., 76.]])

In [152]:
vec1 = torch.tensor([1,2])
vec2 = torch.tensor([3,4])
# dot product
torch.dot(vec1, vec2)

tensor(11)

In [154]:
torch.transpose(a, 0,1)

tensor([[1., 5.],
        [3., 7.]])

In [157]:
h = torch.randint(size=(3,3), low=1, high=4, dtype= torch.float32)
h

tensor([[3., 2., 3.],
        [3., 2., 1.],
        [3., 1., 2.]])

In [158]:
torch.det(h)

tensor(-6.)

In [159]:
torch.inverse(h)

tensor([[-5.0000e-01,  1.6667e-01,  6.6667e-01],
        [ 5.0000e-01,  5.0000e-01, -1.0000e+00],
        [ 5.0000e-01, -5.0000e-01,  2.9802e-08]])

Comparison Operations

In [163]:
i = torch.randint(size=(2,2), low=1, high=5, dtype=torch.float32)
j = torch.randint(size=(2,2), low=1, high=5, dtype=torch.float32)
i, j

(tensor([[1., 4.],
         [2., 2.]]),
 tensor([[2., 1.],
         [2., 1.]]))

In [168]:
i > j

i < j

i == j

i != j


tensor([[ True,  True],
        [False,  True]])

Speical Functions

In [169]:
a

tensor([[1., 3.],
        [5., 7.]])

In [ ]:
torch.log(a)
torch.exp(a)
torch.sqrt(a)
torch.sigmoid(a)
torch.softmax(a, dim=0)
torch.relu(a)

tensor([[1., 3.],
        [5., 7.]])

Inplace Operations

In [178]:
a.add_(b)

tensor([[ 3.,  7.],
        [11., 15.]])

In [180]:
a.relu_()

tensor([[ 3.,  7.],
        [11., 15.]])

Copy Tensor

In [183]:
id(a)

1927426742608

In [184]:
z = a.clone()

In [185]:
id(z)

1927170268512

Tensor Operations on GPU

In [195]:
isGPU = torch.cuda.is_available()
isGPU

False

In [196]:
if isGPU:
    device = torch.device('cuda')

    # Making the tensor on GPU
    x = torch.rand((2,3), device)

    # Moving on existing tensor to GPU
    a = a.to(device)

Comparison of Time

In [198]:
import time

size = 10_000

m_cpu1 = torch.randint(size=(size,size), low=1, high=5, dtype=torch.float32)
m_cpu2 = torch.randint(size=(size,size), low=1, high=5, dtype=torch.float32)

start_time = time.time()
result_cpu = torch.matmul(m_cpu1, m_cpu2)
cpu_time = time.time() - start_time

print(f'Time on CPU {cpu_time:.4f} seconds')

if isGPU:
    m_gpu1 = m_cpu1.to(device)
    m_gpu2 = m_cpu2.to(device)

    start_time = time.time()
    result_cpu = torch.matmul(m_gpu1, m_gpu2)
    gpu_time = time.time() - start_time
    
    torch.cuda.synchronize()

    print(f'Time on GPU {gpu_time:.4f} seconds')

Time on CPU 20.5568 seconds


Reshape Tensors

In [202]:
w = torch.ones(4,4)
w

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [205]:
w.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [207]:
w.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])